MandarinMedien\MMCmfRoutingBundle\Entity\NodeRoute:
    type: entity
    table: null
    inheritanceType: SINGLE_TABLE
    discriminatorMap:
        default: NodeRoute
        auto: AutoNodeRoute
        alias: AliasNodeRoute
        redirect: RedirectNodeRoute

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        route:
            type: string
            length: 255
            unique: true

    manyToOne:
        node:
            targetEntity: MandarinMedien\MMCmfNodeBundle\Entity\Node
            inversedBy: routes
            nullable: false

    lifecycleCallbacks: {  }
