MandarinMedien\MMCmfRoutingBundle\Entity\NodeRoute:
    type: entity
    table: null
    inheritanceType: SINGLE_TABLE
    discriminatorMap:
        default: NodeRoute
        auto: AutoNodeRoute
        alias: AliasNodeRoute
        redirect: RedirectNodeRoute
        external: ExternalNodeRoute

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        route:
            type: string
            length: 255
            unique: true

    lifecycleCallbacks: {  }
