services:
      mm_cmf_routing.node_converter:
          class: MandarinMedien\MMCmfRoutingBundle\Request\NodeParamConverter
          arguments: ["@doctrine.orm.entity_manager"]
          tags:
              - {name: request.param_converter, priority: 1, converter: mm_cmf_routing.node_converter }

      mm_cmf_routing.routing_loader:
          class: MandarinMedien\MMCmfRoutingBundle\Routing\NodeRouteLoader
          arguments: ["@doctrine.orm.entity_manager", "mm_cmf_routing.route_loader._controller"]
          tags:
              - { name: routing.loader }
