services:
      mm_cmf_routing.node_converter:
          class: MandarinMedien\MMCmfRoutingBundle\Request\NodeParamConverter
          arguments: ["@doctrine.orm.entity_manager"]
          tags:
              - {name: request.param_converter, priority: 1, converter: mm_cmf_routing.node_converter }

      mm_cmf_routing.routing_loader:
          class: MandarinMedien\MMCmfRoutingBundle\Routing\NodeRouteLoader
          arguments: ["@doctrine.orm.entity_manager", "mm_cmf_routing.route_loader._controller"]
          tags:
              - { name: routing.loader }

      mm_cmf_routing.node_route_type:
          class: MandarinMedien\MMCmfRoutingBundle\Form\Type\NodeRouteType
          arguments: [@doctrine.orm.entity_manager]
          tags:
              - {name: form.type, alias: node_route_type}

      mm_cmf_routing.node_route_manager:
          class: MandarinMedien\MMCmfRoutingBundle\Entity\NodeRouteManager
          arguments: [@doctrine.orm.entity_manager]

      mm_cmf_routing.validator.node_route_unique:
          class: MandarinMedien\MMCmfRoutingBundle\Validator\Constraints\NodeRouteUniqueValidator
          calls:
              - ["setManager", [@doctrine.orm.entity_manager]]
          tags:
              - { name: validator.constraint_validator, alias: "node_route_unique" }

      mm_cmf_routing.listener:
          class: MandarinMedien\MMCmfRoutingBundle\EventListener\NodeRouteUpdater
          #arguments: [@mm_cmf_routing.node_route_manager]
          tags:
              - {name: doctrine.event_listener, event: prePersist}
              - {name: doctrine.event_listener, event: preUpdate}
              - {name: doctrine.event_listener, event: postFlush}

