services:

      mm_cmf_routing.node_converter:
          class: MandarinMedien\MMCmfRoutingBundle\Request\NodeParamConverter
          arguments: ["@doctrine.orm.entity_manager"]
          tags:
              - {name: request.param_converter, priority: 1, converter: mm_cmf_routing.node_converter }

      mm_cmf_routing.node_route_converter:
            class: MandarinMedien\MMCmfRoutingBundle\Request\NodeRouteParamConverter
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - {name: request.param_converter, priority: 1, converter: mm_cmf_routing.node_route_converter }

      mm_cmf_routing.node_route_type:
          class: MandarinMedien\MMCmfRoutingBundle\Form\Type\NodeRouteType
          arguments: ["@doctrine.orm.entity_manager"]
          tags:
              - {name: form.type, alias: node_route_type}


      mm_cmf_routing.node_route_factory:
          class: MandarinMedien\MMCmfRoutingBundle\Entity\NodeRouteFactory
          arguments: ["@doctrine.orm.entity_manager"]


      mm_cmf_routing.node_route_manager:
          class: MandarinMedien\MMCmfRoutingBundle\Entity\NodeRouteManager
          arguments: ["@doctrine.orm.entity_manager"]


      # Validation Constraints
      mm_cmf_routing.validator.node_route_unique:
          class: MandarinMedien\MMCmfRoutingBundle\Validator\Constraints\NodeRouteUniqueValidator
          calls:
              - ["setManager", ["@doctrine.orm.entity_manager"]]
          tags:
              - { name: validator.constraint_validator, alias: "node_route_unique" }


      # Doctrine Event Listener
      mm_cmf_routing.listener:
          class: MandarinMedien\MMCmfRoutingBundle\EventListener\AutoNodeRouteUpdateListener
          arguments: ["@service_container"]
          tags:
              - {name: doctrine.event_listener, event: prePersist}
              - {name: doctrine.event_listener, event: onFlush}
              - {name: doctrine.event_listener, event: postFlush}

      mm_cmf_routing.node_route_controller:
          class: MandarinMedien\MMCmfRoutingBundle\Controller\NodeRouteController
          calls:
              - ["setContainer", ["@service_container"]]

      mm_cmf_routing.node_resolver:
          class: MandarinMedien\MMCmfRoutingBundle\Resolver\NodeResolver
          arguments: ["@doctrine.orm.entity_manager"]



