<?php

namespace MandarinMedien\MMCmfRoutingBundle\Entity;

/**
 * NodeRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRouteRepository extends \Doctrine\ORM\EntityRepository
{
}
